apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-pupk
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pvij-tenant/rhtap-demo-app/hacbs-test-project-pupk@sha256:1581dc0af1b559d11eb2e7d36023392394474e62a18eb3fe83be8162b552d9d4
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
